Improved pattern-matcher script.

diff --git a/pattern-matcher/minizinc/pattern-matcher b/pattern-matcher/minizinc/pattern-matcher
--- a/pattern-matcher/minizinc/pattern-matcher
+++ b/pattern-matcher/minizinc/pattern-matcher
@@ -77,7 +77,13 @@ function exe {
 }
 
 function exitIfFailed {
-    if [ $? -ne 0 ]; then
+    status=$?
+    if [[ $status != 0 ]]; then
+        if [ ! -z "$@" ]; then
+            echoerr "$@ (exit status $status)"
+        else
+            echoerr "Terminated with exit status $status"
+        fi
         exit 1
     fi
 }
@@ -125,7 +131,7 @@ TMP_DIR=`mktemp -d`
 if [ ! -d "$TMP_DIR" ]; then
     echoerr "Failed to create temporary directory"
 fi
-reportNewEntity $TMP_DIR
+reportNewEntity "$TMP_DIR"
 
 # Set filepath variables
 MINIZINC_PARAMS_FILEPATH="$TMP_DIR/$MINIZINC_PARAMS_FILENAME"
@@ -136,43 +142,37 @@ MINIZINC_ERROR_FILEPATH="$TMP_DIR/$MINIZINC_ERROR_FILENAME"
 echo "* Generating MiniZinc parameter file..."
 exe "$THIS_DIR/mzn-params-gen $MODEL_PARAMS_FILEPATH" \
     "  > $MINIZINC_PARAMS_FILEPATH"
-exitIfFailed
-reportNewEntity $MINIZINC_PARAMS_FILEPATH
+exitIfFailed ""
+reportNewEntity "$MINIZINC_PARAMS_FILEPATH"
 
 echo "* Creating MiniZinc model file..."
-ensureFileExists $MINIZINC_PARAMS_FILEPATH
 exe "cat $MINIZINC_BASE_MODEL_FILEPATH > $MINIZINC_FULL_MODEL_FILEPATH"
-exitIfFailed
-ensureFileExists $MINIZINC_FULL_MODEL_FILEPATH
-echo >> $MINIZINC_FULL_MODEL_FILEPATH
-echo >> $MINIZINC_FULL_MODEL_FILEPATH
-echo >> $MINIZINC_FULL_MODEL_FILEPATH
+exitIfFailed ""
+echo >> "$MINIZINC_FULL_MODEL_FILEPATH"
+echo >> "$MINIZINC_FULL_MODEL_FILEPATH"
+echo >> "$MINIZINC_FULL_MODEL_FILEPATH"
 exe "cat $MINIZINC_PARAMS_FILEPATH >> $MINIZINC_FULL_MODEL_FILEPATH"
-exitIfFailed
-reportNewEntity $MINIZINC_FULL_MODEL_FILEPATH
+exitIfFailed ""
+reportNewEntity "$MINIZINC_FULL_MODEL_FILEPATH"
 
 echo "* Running MiniZinc solver..."
 WORKING_DIR=`pwd`
-cd $TMP_DIR
+cd "$TMP_DIR"
 exe "$MATCHER_MINIZINC_BIN -a $MINIZINC_FULL_MODEL_FILENAME" \
     "  > $MINIZINC_OUTPUT_FILEPATH 2> $MINIZINC_ERROR_FILEPATH"
-STATUS=$?
-if [ $STATUS -ne 0 ]; then
-    echoerr "minizinc exited with failure"
-    cat $MINIZINC_ERROR_FILEPATH
-    exit 1
-fi
-cd $WORKING_DIR
-reportNewEntity $MINIZINC_OUTPUT_FILEPATH
+solver_exit_status=$?
+error_msg=`cat $MINIZINC_ERROR_FILEPATH`
+$( exit $solver_exit_status ) # Restore $? to exit status of the solver
+exitIfFailed "$error_msg"
+cd "$WORKING_DIR"
+reportNewEntity "$MINIZINC_OUTPUT_FILEPATH"
 
 echo "* Converting MiniZinc solution to JSON format..."
-ensureFileExists $MINIZINC_OUTPUT_FILEPATH
 exe "$THIS_DIR/mzn-solution-to-json $MINIZINC_OUTPUT_FILEPATH" \
     "  > $JSON_OUTPUT_FILEPATH"
-exitIfFailed
-ensureFileExists $JSON_OUTPUT_FILEPATH
-reportNewEntity $JSON_OUTPUT_FILEPATH
+exitIfFailed ""
+reportNewEntity "$JSON_OUTPUT_FILEPATH"
 
 echo "* Cleaning up temporary files..."
 exe "rm -rf $TMP_DIR"
-exitIfFailed
+exitIfFailed ""
