Improved error handling in solver script. Also refactored some of its code.

diff --git a/solvers/minizinc/solver b/solvers/minizinc/solver
--- a/solvers/minizinc/solver
+++ b/solvers/minizinc/solver
@@ -104,43 +104,48 @@ function echowarn {
 # Executes a bash command.
 #
 # $1: Command string.
-# $2: File to pipe stderr.
+# $2: Boolean flag (values 0 and 1) whether to terminate if the command exits
+#     with any status code other than 0. Default value is 1.
+# $3: File to pipe STDERR. If no file is given, whatever is written to STDERR
+#     will be redirected to STDOUT and labeled appropriately depending on the
+#     exit code (0 means warning, anything else means errors).
 function exe {
-    if [ -z "$2" ]; then
-        ERROR_LOG=`mktemp`
-        DEL_ERROR_LOG=1
+    if [ -z "$2" ] || [ $2 -ne 0 ]; then
+        term_on_error=1
     else
-        ERROR_LOG="$2"
-        DEL_ERROR_LOG=0
+        term_on_error=0
     fi
-    cmd="$1 2> $ERROR_LOG"
+    if [ -z "$3" ]; then
+        error_log=`mktemp`
+        del_error_log=1
+    else
+        error_log="$2"
+        del_error_log=0
+    fi
+
+    cmd="$1 2> $error_log"
     echo -e "  [${C_INFO}EXECUTING${C_NONE}] $cmd"
     eval "$cmd"
     status=$?
-    if [ -f "$ERROR_LOG" ]; then
-        errors=`cat $ERROR_LOG`
-        if [ -n "$errors" ]; then
+    if [ -f "$error_log" ]; then
+        errors=`cat $error_log`
+    else
+        errors=""
+    fi
+    if [ -n "$errors" ] && [ $del_error_log -eq 1 ]; then
+        if [ $status -eq 0 ]; then
             reportWarning "$errors"
-        fi
-    fi
-    if [ $DEL_ERROR_LOG -ne 0 ]; then
-        rm -f "$ERROR_LOG"
-    fi
-    $( exit $status ) # Restore $? to exit status of the exe command
-}
-
-function exitIfFailed {
-    status=$?
-    if [[ $status != 0 ]]; then
-        if [ ! -z "$@" ]; then
-            reportError "$@ (exit status $status)"
-            echoerr
         else
-            reportError "Terminated with exit status $status"
-            echoerr
+            reportError "$errors"
         fi
+    fi
+    if [ $del_error_log -ne 0 ]; then
+        rm -f "$error_log"
+    fi
+    if [ $status -ne 0 ] && [ $term_on_error -eq 1 ]; then
         exit 1
     fi
+    $( exit $status ) # Restore $? to exit status of the exe command
 }
 
 function ensureFileExists {
@@ -188,10 +193,7 @@ function flattenModelFile {
     command="$command mzn2fzn -G $MINIZINC_GLOBALS_DIR"
     command="$command ${MINIZINC_FULL_MODEL_FILEPATH##*/}"
     exe "$command"
-    solver_exit_status=$?
     reportLatestTimeFromStats
-    $( exit $solver_exit_status ) # Restore $? to exit status of the solver
-    exitIfFailed ""
     reportNewEntity "$fzn_filepath"
     reportNewEntity "${MINIZINC_FULL_MODEL_FILEPATH%.*}.ozn"
     reportUpdatedEntity "$stats_filepath"
@@ -205,9 +207,7 @@ function inflateSolutionFile {
     tmp_file="$MINIZINC_SOLUTION_FILEPATH.tmp"
     reportTask "Inflating MiniZinc solution file"
     exe "solns2out ${ozn_filepath##*/} < ${szn_filepath##*/} > $tmp_file"
-    exitIfFailed ""
     exe "mv $tmp_file $MINIZINC_SOLUTION_FILEPATH"
-    exitIfFailed ""
     reportUpdatedEntity "$MINIZINC_SOLUTION_FILEPATH"
 }
 
@@ -217,9 +217,7 @@ function purgeIntermediateSolutions {
     cmd="$THIS_DIR/purge-intermediate-solutions $MINIZINC_SOLUTION_FILEPATH \
          > $tmp_file"
     exe "$cmd"
-    exitIfFailed ""
     exe "mv $tmp_file $MINIZINC_SOLUTION_FILEPATH"
-    exitIfFailed ""
     reportUpdatedEntity "$MINIZINC_SOLUTION_FILEPATH"
 }
 
@@ -259,18 +257,22 @@ function executeSolver {
     fi
     command="$command ${MINIZINC_FULL_MODEL_FILENAME%.*}.fzn"
     command="$command > $MINIZINC_SOLUTION_FILEPATH"
-    exe "$command" "$MINIZINC_ERROR_FILEPATH"
-    solver_exit_status=$?
+    exe "$command" 0 "$MINIZINC_ERROR_FILEPATH"
+    exit_status=$?
     reportLatestTimeFromStats
-    if [[ $solver_exit_status == 124 ]]; then
+    if [[ $exit_status == 124 ]]; then
         # Solver timed out
-        solver_exit_status=0
+        exit_status=0
     fi
     cleanupErrorFile
     error_msg=`cat $MINIZINC_ERROR_FILEPATH`
-    $( exit $solver_exit_status ) # Restore $? to exit status of the solver
-    exitIfFailed "$error_msg"
-    warnAboutPotentialErrors
+    $( exit $exit_status ) # Restore $? to exit status of the solver
+    if [ $exit_status -ne 0 ]; then
+        reportError "$error_msg"
+        exit 1
+    else
+        warnAboutPotentialErrors
+    fi
     reportNewEntity "$MINIZINC_SOLUTION_FILEPATH"
     reportUpdatedEntity "$stats_filepath"
 
@@ -371,35 +373,29 @@ MINIZINC_ERROR_FILEPATH="$TMP_DIR/$MINIZINC_ERROR_FILENAME"
 
 reportTask "Extending model instance with match sizes"
 exe "$THIS_DIR/size-extender $JSON_INPUT_FILEPATH > $JSON_EXT_FILEPATH"
-exitIfFailed
 reportNewEntity $JSON_EXT_FILEPATH
 
 reportTask "Converting constraints into parameter data"
 cmd="$THIS_DIR/constraints-converter $JSON_EXT_FILEPATH \
      > $JSON_EXT2_FILEPATH"
 exe "$cmd"
-exitIfFailed
 reportNewEntity $JSON_EXT2_FILEPATH
 
 reportTask "Generating MiniZinc parameter file"
 exe "$THIS_DIR/json2params $JSON_EXT2_FILEPATH > $MINIZINC_PARAMS_FILEPATH"
-exitIfFailed
 reportNewEntity $MINIZINC_PARAMS_FILEPATH
 
 reportTask "Generating MiniZinc model file"
 exe "cat $MINIZINC_BASE_MODEL_FILEPATH > $MINIZINC_FULL_MODEL_FILEPATH"
-exitIfFailed ""
 echo >> "$MINIZINC_FULL_MODEL_FILEPATH"
 echo >> "$MINIZINC_FULL_MODEL_FILEPATH"
 echo >> "$MINIZINC_FULL_MODEL_FILEPATH"
 exe "cat $MINIZINC_PARAMS_FILEPATH >> $MINIZINC_FULL_MODEL_FILEPATH"
-exitIfFailed ""
 reportNewEntity "$MINIZINC_FULL_MODEL_FILEPATH"
 
 MINIZINC_FULL_MODEL_SAVE_PATH="$JSON_OUTPUT_DIR/$JSON_INPUT_FILENAME.mzn"
 reportTask "Saving MiniZinc model for later evaluation"
 exe "cp $MINIZINC_FULL_MODEL_FILEPATH $MINIZINC_FULL_MODEL_SAVE_PATH"
-exitIfFailed ""
 reportNewEntity "$MINIZINC_FULL_MODEL_SAVE_PATH"
 
 prev_dir=`pwd`
@@ -416,19 +412,16 @@ reportTask "Converting MiniZinc solution to JSON format"
 cmd="$THIS_DIR/solution2json $MINIZINC_SOLUTION_FILEPATH \
      > $JSON_SOLUTION_FILEPATH"
 exe "$cmd"
-exitIfFailed ""
 reportNewEntity "$JSON_SOLUTION_FILEPATH"
 
 reportTask "Converting MiniZinc statistics to JSON format"
 exe "$THIS_DIR/stats2json $MINIZINC_STATS_FILEPATH > $JSON_STATS_FILEPATH"
-exitIfFailed ""
 reportNewEntity "$JSON_STATS_FILEPATH"
 
 reportTask "Merging JSON files"
 cmd="$THIS_DIR/merge-jsons $JSON_SOLUTION_FILEPATH $JSON_STATS_FILEPATH \
      > $JSON_OUTPUT_FILEPATH"
 exe "$cmd"
-exitIfFailed ""
 reportNewEntity "$JSON_OUTPUT_FILEPATH"
 
 echo
