Improved checker.

diff --git a/testing/Makefile b/testing/Makefile
--- a/testing/Makefile
+++ b/testing/Makefile
@@ -483,6 +483,28 @@ pattern.dot:
 	else \
 		echo "[$(C_IGNORED)IGNORED$(C_NONE)] (not found)" ;\
 	fi
+	@echo -n "    $*.de.lp.ep.ce.cc.rp.de.rt.be.f.json (presolved) "
+	@if [ -f $*.de.lp.ep.ce.cc.rp.de.rt.be.f.json ]; then \
+		if [ -f $*.de.lp.ep.ce.cc.rp.de.rt.be.ae.presolved.p.json ]; then \
+			out=`mktemp` ;\
+			msg=`$(UNI_IS_CMD) \
+					 check --check-fun-coverage \
+			         -f $*.de.lp.ep.ce.cc.rp.de.rt.be.f.json \
+			         -p $*.de.lp.ep.ce.cc.rp.de.rt.be.ae.presolved.p.json \
+					 > $$out 2>&1` ;\
+			if [ "$$?" -eq "0" ]; then \
+				echo "[$(C_OK)OK$(C_NONE)]" ;\
+			else \
+				echo "[$(C_ERROR)FAILED$(C_NONE)]" ;\
+				cat $$out ;\
+			fi \
+		else \
+			echo "[$(C_IGNORED)IGNORED$(C_NONE)] (has no pattern matchset)" ;\
+		fi \
+	else \
+		echo "[$(C_IGNORED)IGNORED$(C_NONE)] (not found)" ;\
+	fi
+
 	@echo "$(C_INFO)* CHECKING OVERLAP OF DATA LOCATIONS$(C_NONE)"
 	@echo -n "    $*.de.lp.ep.ce.cc.rp.de.rt.be.f.json "
 	@if [ -f $*.de.lp.ep.ce.cc.rp.de.rt.be.f.json ]; then \
